name = "hex-gf2-mathlib"
defaultTargets = ["HexGF2Mathlib"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexGF2"
git = "https://github.com/leanprover/hex-gf2.git"
rev = "3070a7940c865cef6e19e659bea5ee4a3d806ee8"

[[require]]
name = "HexPolyFp"
git = "https://github.com/leanprover/hex-poly-fp.git"
rev = "63d11e9652020e83629808977bff618e99d21234"

[[require]]
name = "HexGFqField"
git = "https://github.com/leanprover/hex-gfq-field.git"
rev = "fae308f2920311382cbb8248546566c5baa2f740"

[[require]]
name = "HexPolyFpMathlib"
git = "https://github.com/leanprover/hex-poly-fp-mathlib.git"
rev = "d6f95baf8dc463f72423dfb3f7260892701b2fda"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.33.0-rc1"

[[lean_lib]]
name = "HexGF2Mathlib"
