name = "hex-gf2-mathlib"
defaultTargets = ["HexGF2Mathlib"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexGF2"
git = "https://github.com/leanprover/hex-gf2.git"
rev = "0230464ace6ba2929b60f89e7956de2bf98059a7"

[[require]]
name = "HexPolyFp"
git = "https://github.com/leanprover/hex-poly-fp.git"
rev = "6bb30a50196b830b5faeead8580b1bd889069717"

[[require]]
name = "HexGFqField"
git = "https://github.com/leanprover/hex-gfq-field.git"
rev = "b6cece729c1ba9ea5250859ae59e7f007378bacc"

[[require]]
name = "HexPolyFpMathlib"
git = "https://github.com/leanprover/hex-poly-fp-mathlib.git"
rev = "6e589eed50000bfd1354c955ef940fcf7df02f72"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.34.0-rc2"

[[require]]
name = "HexBasic"
git = "https://github.com/leanprover/hex-basic.git"
rev = "1a0fff2c8f545753b01cff0d941bf48f945cd299"

[[lean_lib]]
name = "HexGF2Mathlib"
