name = "hex-gf2-mathlib"
defaultTargets = ["HexGF2Mathlib"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexGF2"
git = "https://github.com/leanprover/hex-gf2.git"
rev = "264ff5035e3ca7df7e5e18df6e780e83766d7fbf"

[[require]]
name = "HexPolyFp"
git = "https://github.com/leanprover/hex-poly-fp.git"
rev = "1ca7698307ed776c90e1cd796527d432913bd518"

[[require]]
name = "HexGFqField"
git = "https://github.com/leanprover/hex-gfq-field.git"
rev = "a501c8c86a05cb7243ea6362654fcbf1394e5904"

[[require]]
name = "HexPolyFpMathlib"
git = "https://github.com/leanprover/hex-poly-fp-mathlib.git"
rev = "c4f4cc93006daf0f41013fb072d91327b9c42f09"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.34.0-rc2"

[[lean_lib]]
name = "HexGF2Mathlib"
